---
title: "solar"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(tidyverse)
library(lubridate)
theme_set(theme_light())
```

```{r}
solar_elec <- rio::import("06 EXCEL model and data -- Wells Fargo.xlsx", sheet = "Demand and Solar Output") %>% 
  janitor::clean_names() %>% 
  as_tibble()

elec_px <- rio::import("06 EXCEL model and data -- Wells Fargo.xlsx", sheet = "Electricity Prices") %>% 
  janitor::clean_names() %>% 
  as_tibble()
```
```{r}
df <- solar_elec %>%
  mutate(yr = year(date_time), mth = month(date_time)) %>% 
  group_by(yr, mth) %>% 
  summarise(across(electricity_demand_for_the_branch_k_w:solar_system_output_k_w, sum)) %>% 
  left_join(
    elec_px %>% 
      mutate(yr = year(month), mth = month(month)) %>% 
      select(-month)
  )
```

```{r}
df %>% 
  summarise(sum(solar_system_output_k_w * electricity_price_k_wh) / sum(solar_system_output_k_w)) # weighted average price for 2013

```

## Net Metering

In total energy generated is smaller than total consumption
```{r}
solar_elec %>% 
  select(-date_time) %>% 
  summarize_all(sum)
```

However to each 15 min slot, demand is larger than output only 83.6% 
```{r}
solar_elec %>% 
  mutate(not_satisfied = electricity_demand_for_the_branch_k_w > solar_system_output_k_w) %>% 
  summarise(mean(not_satisfied))
```

```{r}
solar_elec %>% 
  gather(key, value,-date_time) %>% 
  ggplot(aes(date_time, value, color = key))+
  geom_line()+
  labs(title = "Demand were sometimes outstriped by output",
       x= "", y="", color = "")+
  theme(legend.position = "bottom")
```

```{r}
solar_elec %>% 
  mutate(unmet_demand = electricity_demand_for_the_branch_k_w - solar_system_output_k_w) %>% 
  ggplot(aes(date_time, unmet_demand))+
  geom_point(aes(color = unmet_demand > 0 ))+
  labs(title = "There are net metering situation frequently",
       x="",y="unmet demand")+
  theme(legend.position = "None")
```

```{r}
solar_elec %>% 
  mutate(unmet_demand = electricity_demand_for_the_branch_k_w - solar_system_output_k_w) %>% 
  ggplot(aes(unmet_demand))+
  geom_histogram()+
  geom_vline(xintercept = 0, lty =2)+
  labs(title = "Distribution of unmet demand",
       x="",y="")
```

